---
abstract: 'Pick a YAML implementation and use it'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SHARYANTO-YAML-Any
requires:
  YAML::Syck: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/SHARYANTO-YAML-Any/
  repository: http://github.com/sharyanto/perl-SHARYANTO-YAML-Any
version: 0.56
