---
abstract: 'SHARYANTO::YAML::Any - Pick a YAML implementation and use it.'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102343, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SHARYANTO-YAML-Any
resources:
  homepage: http://search.cpan.org/dist/SHARYANTO-YAML-Any/
  repository: http://github.com/sharyanto/perl-SHARYANTO-YAML-Any
version: 0.721
